sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile

scala:
  - 2.11.8

jdk:
  - openjdk7
  - oraclejdk7

notifications:
  email:
    - mietkins7@gmail.com
